# Generated by Django 4.2.7 on 2023-12-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockAI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=100)),
                ('startDate', models.DateField()),
                ('predictedValue', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='StockPrediction',
        ),
    ]
