# Generated by Django 4.2.7 on 2023-12-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockAI', '0002_react_delete_stockprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('prediction', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='React',
        ),
    ]
