# Generated by Django 4.2.7 on 2023-12-14 03:27

from django.db import migrations, models
import stockAI.models


class Migration(migrations.Migration):

    dependencies = [
        ('stockAI', '0003_stockprediction_delete_react'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprediction',
            name='start_date',
            field=models.DateField(blank=True, default=stockAI.models.get_default_date),
        ),
        migrations.AlterField(
            model_name='stockprediction',
            name='ticker',
            field=models.CharField(default='na', max_length=10),
        ),
    ]
