# Generated by Django 4.2.7 on 2023-12-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockAI', '0004_alter_stockprediction_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockprediction',
            old_name='start_date',
            new_name='startDate',
        ),
        migrations.RemoveField(
            model_name='stockprediction',
            name='prediction',
        ),
        migrations.AddField(
            model_name='stockprediction',
            name='predictedValue',
            field=models.CharField(default='na', max_length=30),
        ),
        migrations.AlterField(
            model_name='stockprediction',
            name='ticker',
            field=models.CharField(default='na', max_length=30),
        ),
    ]
