# Generated by Django 5.0 on 2023-12-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='react',
            name='predictedValue',
        ),
        migrations.RemoveField(
            model_name='react',
            name='date',
        ),
        migrations.RemoveField(
            model_name='react',
            name='ticker',
        ),
        migrations.AddField(
            model_name='react',
            name='department',
            field=models.CharField(default='Schmoe', max_length=200),
        ),
        migrations.AddField(
            model_name='react',
            name='employee',
            field=models.CharField(default='Joe', max_length=30),
        ),
    ]
