# Generated by Django 5.0 on 2023-12-10 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_react_predictedvalue_remove_react_startdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='react',
            name='department',
        ),
        migrations.RemoveField(
            model_name='react',
            name='employee',
        ),
        migrations.AddField(
            model_name='react',
            name='predictedValue',
            field=models.CharField(default='na', max_length=30),
        ),
        migrations.AddField(
            model_name='react',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='react',
            name='ticker',
            field=models.CharField(default='na', max_length=30),
        ),
    ]
